# Generated by Django 4.2.10 on 2024-05-04 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Demand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=100)),
                ('Second_Name', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=200)),
                ('Phone_Number', models.CharField(max_length=100)),
                ('Affiliation', models.CharField(max_length=100)),
                ('Research_Area', models.CharField(max_length=100)),
                ('Position', models.CharField(max_length=100)),
                ('CV', models.FileField(upload_to='CV/')),
                ('Motivation', models.TextField(default='')),
                ('Contribution', models.TextField(default='')),
                ('References', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=100)),
                ('Second_Name', models.CharField(max_length=100)),
                ('Email', models.CharField(blank=True, max_length=200, null=True)),
                ('Phone_Number', models.CharField(blank=True, max_length=100, null=True)),
                ('Affiliation', models.CharField(blank=True, max_length=100, null=True)),
                ('Research_Area', models.CharField(blank=True, max_length=100, null=True)),
                ('Position', models.CharField(blank=True, max_length=100, null=True)),
                ('CV', models.FileField(blank=True, null=True, upload_to='CV/')),
                ('Motivation', models.TextField(blank=True, default='')),
                ('Contribution', models.TextField(blank=True, default='')),
                ('References', models.TextField(blank=True, default='')),
                ('Biography', models.TextField(default='')),
                ('Location', models.CharField(max_length=100)),
                ('Image', models.ImageField(upload_to='Members_Photos/')),
            ],
        ),
        migrations.CreateModel(
            name='Thrust',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=500)),
                ('Image', models.ImageField(upload_to='thrusts/')),
            ],
        ),
    ]
