# Generated by Django 5.0.6 on 2024-06-05 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='Role',
            field=models.CharField(default='exit', max_length=100),
            preserve_default=False,
        ),
    ]
