# Generated by Django 5.0.6 on 2024-06-05 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_member_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='Role',
            field=models.CharField(default='member', max_length=100),
        ),
    ]
