# Generated by Django 5.0.6 on 2024-06-15 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_member_role'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Demand',
            new_name='Application',
        ),
    ]
