# Generated by Django 5.0.6 on 2024-06-15 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_demand_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='Biography',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='application',
            name='Image',
            field=models.ImageField(default='/media/Members_Photos/default.jpg', upload_to='Members_Photos/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='Status',
            field=models.CharField(default='In Process', max_length=100),
        ),
    ]
