# Generated by Django 5.0.6 on 2024-06-15 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_member_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='Location',
        ),
        migrations.AlterField(
            model_name='member',
            name='Affiliation',
            field=models.CharField(default='MSN-UM6P', max_length=100),
            preserve_default=False,
        ),
    ]
