# Generated by Django 5.0.6 on 2024-06-29 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_member_location_alter_member_affiliation'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=300)),
            ],
        ),
        migrations.AlterField(
            model_name='member',
            name='Image',
            field=models.ImageField(blank=True, default='Members_Photos/default.jpg', upload_to='Members_Photos/'),
        ),
        migrations.CreateModel(
            name='NewsEventImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='NewsEvent/')),
                ('NewsEvent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app.newsevent')),
            ],
        ),
    ]
