# Generated by Django 5.0.6 on 2024-07-03 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_publication_elearning_seminars_webinars_podcast'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pooling_Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Image', models.ImageField(upload_to='Pooling Equipment/')),
                ('Description', models.TextField(default='')),
            ],
        ),
    ]
