# Generated by Django 5.0.6 on 2024-07-03 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_pooling_equipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsevent',
            name='Image',
            field=models.ImageField(default='NewsEvent/default.png', upload_to='NewsEvent/'),
        ),
        migrations.AlterField(
            model_name='pooling_equipment',
            name='Image',
            field=models.ImageField(blank=True, default='Pooling Equipment/default.png', null=True, upload_to='Pooling Equipment/'),
        ),
    ]
